# Generated by Django 4.2.7 on 2023-11-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='Time_Create',
            new_name='Time_Created',
        ),
    ]
